<a href="https://colab.research.google.com/github/mbaliu-treino/Desenvolve/blob/main/LEARN_C_PROG_Python_e_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=tomato> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=tomato> 1. INTRODUÇÃO AO PYTHON
---

## 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

### Verificando versão

In [ ]:
!python --version

Python 3.7.12


# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [1]:
10 + 5

15

### Subtração ($-$)

In [2]:
10 - 3

7

### Multiplicação ($*$)

In [3]:
5 * 2

10

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [4]:
# Divisão normal
5 / 2

2.5

In [5]:
# Partes inteiras
5 // 2

2

### Resto da divisão ($\%$)

In [6]:
# Resto
5 % 2

1

### Exponenciação ($**$)

In [7]:
2 ** 5

32

### Expressões matemáticas

In [9]:
# segue a ordem das expressões da matemática
# Uso de parenteses
2 + 5 * 2

12

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [ ]:
'ele'

'ele'

In [ ]:
_

'ele'

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

<h3> $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [11]:
valor = 5
valor = valor + 2
print(valor)
valor += 2
print(valor)

7
9


### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [13]:
x, y = (10, 5.8)
print(y)

5.8


# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [14]:
type(9)

int

### Booleanos

In [15]:
type(True)

bool

### Strings

In [16]:
type('9')

str

### None

In [18]:
None

In [ ]:
type(None)

NoneType

# 2.4 Conversão de tipos

### Conversões de tipo

Funções int(), float(), str()

In [19]:
int('9')

9

In [20]:
float(9)

9.0

In [21]:
str(9)

'9'

In [22]:
str(9.0)

'9.0'

In [23]:
str(9.000)

'9.0'

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [24]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

Verdadeiro


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [25]:
# Isto é um comentário
ano_atual = 2019
ano_atual

2019

In [26]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

2019

In [27]:
'''Isto é um
comentário'''
ano_atual = 2019
ano_atual

2019

In [28]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

Verdadeiro


### Formatação de *strings*

## *str % valor*
https://docs.python.org/3.6/library/stdtypes.html#old-string-formatting

In [47]:
pais = 'França'

In [50]:
print('Ele foi para %(pais)s.' % {'pais':pais})

Ele foi para França.


## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [51]:
print('Ele foi para {pais}.'.format(pais=pais) )

Ele foi para França.


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [52]:
print(f'Ele foi para {pais}.')

Ele foi para França.


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [53]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

### Lista com tipos de dados variados

In [54]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [55]:
Carro_1[3]

44410.0

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [56]:
'Passat' in Carro_1

False

In [57]:
'Passat' in Carro_2

True

## *A + B*

Concatena as listas *A* e *B*.

In [65]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [60]:
A + B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

Tamanho da lista A.

In [61]:
len(A)

4

# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [62]:
A[0]

'Rodas de liga'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [63]:
A[0:2]

['Rodas de liga', 'Travas elétricas']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena a lista *A*.

In [66]:
print(A)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']


In [67]:
A.sort()

In [68]:
print(A)

['Bancos de couro', 'Piloto automático', 'Rodas de liga', 'Travas elétricas']


## *A.append(x)*

Adiciona o elemento *x* no final da lista *A*.

In [69]:
A.append('Freio')

In [70]:
A

['Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Travas elétricas',
 'Freio']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [71]:
A.pop()

'Freio'

In [72]:
A

['Bancos de couro', 'Piloto automático', 'Rodas de liga', 'Travas elétricas']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [75]:
id(A)

139886591855344

In [76]:
a = A
id(a)

139886591855344

In [78]:
a = A.copy()
id(a)

139886591893328

In [80]:
a = A[:]
id(a)

139886591926672

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [81]:
for i in A:
    print(i)

Bancos de couro
Piloto automático
Rodas de liga
Travas elétricas


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [82]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
# Números pares
[i for i in range(10) if i%2 == 0]

[0, 2, 4, 6, 8]

# 4.2 Loops aninhados

In [86]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [87]:
n = 0
for lista in dados:
    for item in lista:
        n += 1

print(n)

24


## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [92]:
todos = []
for lista in dados:
    todos = todos + lista
len(todos)

24

In [93]:
# Itens únicos
len(set(todos))

17

### List comprehensions

In [96]:
type({i for i in range(5)})

set

# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [97]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [98]:
for carro in dados:
    if carro[2]:
        print(carro[0])

DS5
A5


### List comprehensions

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [ ]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

In [ ]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [100]:
import numpy as np

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

### Importando parte do pacote

In [101]:
from numpy import arange

In [103]:
arange(5.0)

array([0., 1., 2., 3., 4.])

# 5.1 Criando arrays Numpy

## 1.3 Trabalhando com arrays Numpy

In [104]:
import numpy as np

In [ ]:
km = np.loadtxt('/content/carros-km.txt')

In [ ]:
anos = np.loadtxt('carros-anos.txt', dtype=int)

### Obtendo a quilometragem média por ano

In [ ]:
km_media = km / (2019 - anos)

In [ ]:
type(km_media)

numpy.ndarray

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [105]:
x = np.array([2, 3, 1, 0])
x

array([2, 3, 1, 0])

In [106]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [107]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [108]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [110]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [112]:
from io import StringIO   # StringIO behaves like a file object
c = StringIO(u"0 1\n2 3")
np.loadtxt(c)

array([[0., 1.],
       [2., 3.]])

# Comparando desempenho com listas

In [113]:
py_list = list(range(1000000))
np_array = np.arange(1000000)

In [114]:
%%time
for _ in range(100): 
    py_list = [x * 2 for x in py_list]

CPU times: user 10 s, sys: 2.36 s, total: 12.4 s
Wall time: 12.4 s


In [115]:
%%time
for i in range(100):
    data = range(1000000)
    result = [x**2 for x in py_list]

CPU times: user 32.3 s, sys: 2.68 s, total: 35 s
Wall time: 35.1 s


In [116]:
%%time
for i in range(100):
    data = range(1000000)
    result = [x**2 for x in range(1000000)]

CPU times: user 29.3 s, sys: 914 ms, total: 30.2 s
Wall time: 30.3 s


In [117]:
%%time 
for _ in range(100): 
    result = np_array ** 2

CPU times: user 157 ms, sys: 7.69 ms, total: 165 ms
Wall time: 165 ms


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

O Array do numpy suporta operações com valores constantes, diferentemente da lista padrão do Python.

In [118]:
km_list = [44410., 5712., 37123., 0., 25757.]
anos_list = [2003, 1991, 1990, 2019, 2006]

In [119]:
idade_list = anos_list - 2022

TypeError: ignored

In [120]:
km_np = np.array([44410., 5712., 37123., 0., 25757.])
anos_np = np.array([2003, 1991, 1990, 2019, 2006])

In [124]:
idade_np = abs(anos_np - 2022)
idade_np

array([19, 31, 32,  3, 16])

### Operações entre arrays

In [ ]:
km_media = km_np / idade_np

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

`ndarray[ linha ][ coluna ]*` ou 

`*ndarray[ linha, coluna ]`

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

In [125]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'feminino']
    ]
)

# Seleciona somente as duas primeiras colunas
dados[:, :2]

array([['Roberto', 'casado'],
       ['Sheila', 'solteiro'],
       ['Bruno', 'solteiro'],
       ['Rita', 'casado']], dtype='<U9')

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [ ]:
contador = np.arange(10)

In [ ]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
contador[contador > 5]

array([6, 7, 8, 9])

In [ ]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'feminino']
    ]
)

dados[:, :2][dados[:, -1] == 'masculino']

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [ ]:
contador = np.array([np.arange(10), np.arange(10), np.arange(10)])
contador

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

**ndarray.shape**

Retorna uma tupla com as dimensões do array.

In [ ]:
contador.shape

(3, 10)

**ndarray.ndim**

Retorna o número de dimensões do array.

In [ ]:
contador.ndim

2

**ndarray.size**

Retorna o número de elementos do array.

In [ ]:
contador.size

30

**ndarray.dtype**

Retorna o tipo de dados dos elementos do array.

In [ ]:
contador.dtype

dtype('int64')

**ndarray.T**

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [ ]:
contador.T

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6],
       [7, 7, 7],
       [8, 8, 8],
       [9, 9, 9]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

**ndarray.tolist()**

Retorna o array como uma lista Python. Converte todas dimensões em listas.


In [ ]:
contador.tolist()

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [ ]:
list(contador)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

**ndarray.reshape(shape[, order])**

Retorna um array que contém os mesmos dados com uma nova forma.

In [ ]:
cont = np.arange(10)

In [ ]:
cont.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
cont.reshape((5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
cont.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
km + anos
## Retorna um objeto pouco útil

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [ ]:
np.array(km + anos).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [ ]:
np.array(km + anos).reshape((5,2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

**ndarray.resize(new_shape[, refcheck])**

Altera a forma e o tamanho do array.

In [ ]:
dn = dados[:]

In [ ]:
dados.resize((3,5), refcheck=False)

array([['Roberto', 'casado', 'masculino', 'Sheila', 'solteiro'],
       ['feminino', 'Bruno', 'solteiro', 'masculino', 'Rita'],
       ['casado', 'feminino', '', '', '']], dtype='<U9')

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [ ]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

**np.mean()**

Retorna a média dos elementos do array ao longo do eixo especificado.

**np.std()**

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

**ndarray.sum()**

Retorna a soma dos elementos do array ao longo do eixo especificado.

**np.sum()**

Retorna a soma dos elementos do array ao longo do eixo especificado.